name-template: "Release BE"
tag-template: "release-be-$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feat"
      - "task"
      - "chore"

  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"

  - title: "⚙️ Workflow"
    labels:
      - "ci"

  - title: "🛠 Infra"
    labels:
      - "infra"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

autolabeler:
  - label: "fix"
    title:
      - "/fix:/i"

  - label: "feat"
    title:
      - "/feat:/i"

  - label: "task"
    title:
      - "/task:/i"

template: |
  ## Backend & Infrastructure Changes

  $CHANGES