name: Release Drafter - BE/INFRA

on:
  push:
    branches:
      - "release/*"
    paths:
      - "backend/**"
      - "infra/**"
      - ".github/**"

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
            config-name: release-drafter-be-infra.yml
            tag: release-be
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup duplicate BE drafts
        run: |
            echo "Fetching BE draft releases..."

            RELEASES=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases)

            IDS=$(echo "$RELEASES" | jq -r '
            [.[] | select(.draft == true and .name == "Release BE")]
            | sort_by(.created_at)
            | reverse
            | .[1:]
            | .[].id
            ')

            for ID in $IDS; do
            echo "Deleting old draft release ID: $ID"
            curl -X DELETE \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/releases/$ID
            done